resources:
  - name: src
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/carbot

pipelines:
  - name: car_pipeline
    steps:
      - name: build
        type: Bash
        configuration:
          affinityGroup: myGroup        
          inputResources:
            - name: src
              trigger: false
        execution:
          onExecute:
            - cd $res_src_resourcePath
            - python -m py_compile calc.py
      - name: train_model
        type: Bash
        configuration:
          affinityGroup: myGroup
          inputSteps:
            - name: build
        execution:
          onExecute:
            - sleep 5
            - echo "Training model completed"
      - name: test_model
        type: Bash
        configuration:
          affinityGroup: myGroup
          inputSteps:
            - name: train_model
          inputResources:
            - name: src
              trigger: false               
        execution:
          onExecute:
            - pip install pytest
            - cd $res_src_resourcePath            
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_src_resourcePath/test-reports/results.xml          
      - name: publish_artifacts
        type: Bash
        configuration:
          inputSteps:
            - name: test_model
        execution:
          onExecute:
            - echo "Publish to RT completed"
