resources:
  - name: src
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/carbot

pipelines:
  - name: car_pipeline
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: src
              trigger: false
        execution:
          onExecute:
            - python -m py_compile application.py
      - name: train_model
        type: Bash
        configuration:
          inputSteps:
            - name: build
        execution:
          onExecute:
            - echo "Unit Test completed"
      - name: test_model
        type: Bash
        configuration:
          inputSteps:
            - name: train_model
        execution:
          onExecute:
            - echo "Xray scan completed"
      - name: publish_artifacts
        type: Bash
        configuration:
          inputSteps:
            - name: test_model
        execution:
          onExecute:
            - echo "Publish to RT completed"
